version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - pip install -r ./shoppingBackend/requirements.txt
      - echo "Checking pytest installation"
      - which pytest
      - pytest --version
      - echo "Installing Docker Compose"
      - curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    
  pre_build:
    commands:
      - echo "Exporting env variables"
      - printenv | grep DB_   # Para ver que están realmente disponibles
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Begining Docker Compose"
      - docker-compose up -d
      - echo "Waiting for database to be ready"
      - |
        until [ "$(docker inspect -f '{{.State.Health.Status}}' shoppingdbServer)" == "healthy" ]; do
          echo "Waiting for DB health check..."; sleep 2;
        done
  build:
    commands:
      - echo "Running Tests"
      - pwd
      - ls -la
      - ls -la shoppingBackend
      - ls -la shoppingBackend/tests
      - pytest shoppingBackend/tests -v

  post_build:
    commands:
      - echo "Stopping services"
      - docker-compose -f docker-compose.yml down
artifacts:
  files:
    - '**/*'