version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - pip install -r ./shoppingBackend/requirements.txt
      - echo "Installing Docker Compose"
      - curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    
  pre_build:
    commands:
      - echo "Begining Docker Compose"
      - docker-compose -f docker-compose.yml up -d
      - echo "Waiting for database to be ready"
      - until docker exec ${DB_HOST} pg_isready -U ${DB_USER}; do echo "Waiting for DB..."; sleep 2; done
  build:
    commands:
      - echo "Running Tests"
      - pytest shoppingBackend/tests
      - ls -R
      - pwd

  post_build:
    commands:
      - echo "Stopping services"
      - docker-compose -f docker-compose.yml down
artifacts:
  files:
    - '**/*'